### ISSUE TITLE
duplicate feature with GLPI core

### ISSUE THREAD

**Issue by orthagh** [FleuryK/GLPICheckingVersion#1]
Hello dear plugin maintainer.

I just received your catalog submission for this plugin.
I asked myself the need of this plugin as GLPI have this feature in Setup > Maintenance menu:

![image](https://user-images.githubusercontent.com/418844/44572550-6b266480-a784-11e8-8617-a584c8644266.png)

![image](https://user-images.githubusercontent.com/418844/44572558-71b4dc00-a784-11e8-9293-5f57a462567c.png)

Maybe i miss something when understanding the plugin purpose.
Could you clarify ?

By the way, thank you very much for your contribution to GLPI Project.

Regards

**Comment by FleuryK** [comment]
Hello,

At first (I knew GLPI 0.8.x), I did not know that this feature was already present in GLPI itself.

So I looked in plugins.glpi-project.org if on the off chance there was not a plugin to check if the version of GLPI we were up to date or not. And I did not find anything.

That's why I created this plugin. It allows to verify if the version of GLPI that one is up to date or not and if it is not up to date, to download it directly.

I had a lot of trouble doing it but with perseverance, I still managed.
